###
POST  https://localhost:5001/api/endereco/create
Content-Type: application/json

{
     
                "Nome": "Roberto",
                "Descricao": "ASDASD",
                "Preco": 2.2
            
}

###
GET   https://localhost:5001/api/endereco/list

###
GET  https://localhost:5001/api/endereco/getid/

###
DELETE   https://localhost:5001/api/endereco/delete/Roberto
