###
POST  https://localhost:5001/api/hotel/create
Content-Type: application/json

{
     
                "Nome": "Roberto",
                "QuantidadeQuartos": 2,
                "Adicionais": "Anão",
                "TipoDeCamas": "King",
                "ImagemHotel": "Jpeg",
                "Cidade": "Cu ritiba"
            
}

###
GET   https://localhost:5001/api/hotel/list

###
GET  https://localhost:5001/api/hotel/getid/6

###
DELETE   https://localhost:5001/api/hotel/delete/Roberto
