###
POST  https://localhost:5001/api/quarto/create
Content-Type: application/json

{
     
                "nomeQuarto": "Teste"
                
}

###
GET   https://localhost:5001/api/quarto/list

###
GET  https://localhost:5001/api/quarto/getid/1

###
DELETE   https://localhost:5001/api/quarto/delete/2
