###
POST  https://localhost:5001/api/quarto/create
Content-Type: application/json

{
 
        "NomeQuarto": "Standard",
        "QuantidadeDeCamas": 1,
        "TipoDeCamas": "Beliche",
        "ImagemQuarto": "https://s2.glbimg.com/NO1Mrkp3Z96htIx8_RhrdHTux0w=/e.glbimg.com/og/ed/f/original/2018/03/08/decoracao-de-quarto-cabeceira-suede-rosa-roupa-de-cama-branco-com-rosa-papel-de-parede-florido-romantico-abajur-e-pendente-brancoarquiteta-leticia-arcangeli.jpg ",
        "Preco": 110.00
        
}


###
GET   https://localhost:5001/api/quarto/listquarto

###
GET  https://localhost:5001/api/quarto/getlistquartoporid/1

###
DELETE   https://localhost:5001/api/quarto/delete/1

###
GET https://localhost:5001/api/quarto/1/reservas

