###
POST  https://localhost:5001/api/quarto/create
Content-Type: application/json

{
     
        "NomeQuarto": "3",
        "QuantidadeDeCamas": 1,
        "TipoDeCamas": "king",
        "ImagemQuarto": "imagem01",
        "Preco": 10.0
        
}


###
GET   https://localhost:5001/api/quarto/listquarto

###
GET  https://localhost:5001/api/quarto/getlistquartoporid/6

###
DELETE   https://localhost:5001/api/quarto/delete/1
//fazer o delete do quarto e do historico junto

//fazer o delete somente do Histórico controler
