
###
POST   https://localhost:5001/api/reserva/create/2/3
Content-Type: application/json

{
    "CheckIn": "2021-08-30",
    "CheckOut": "2021-09-10"
}


###
GET https://localhost:5001/api/reserva/list

###
GET https://localhost:5001/api/reserva/listbyusuario/1