###
POST  https://localhost:5001/api/usuario/create
Content-Type: application/json

{
    "Nome": "andrey",
    "Senha": "jureminha123",
    "Cpf": "093.548.569-32",
    "DataNascimento": "23/06/2000"
    
   
    
    
}


###
GET   https://localhost:5001/api/usuario/list

###
GET  https://localhost:5001/api/usuario/getid/3

###
DELETE   https://localhost:5001/api/usuario/delete/3

