###
POST  https://localhost:5001/api/usuario/create
Content-Type: application/json

{
    "Nome": "claudio",
    "Senha": "jureminha123",
    "Cpf": "093.548.569-32",
    "DataNascimento": "23/06/2000",
    "Endereco": {            
                "Nome": "rogerthat",
                "Descricao": "ASDASD",
                "Preco": 2.2
    } 
}

###
GET   https://localhost:5001/api/usuario/list

###
GET  https://localhost:5001/api/usuario/getid/1

###
DELETE   https://localhost:5001/api/usuario/delete/claudio

